import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Introduction',
          items: ['intro/physical-ai-intro'],
        },
        {
          type: 'category',
          label: 'Module 1: ROS 2',
          items: [
            'module-1-ros2/ros2-fundamentals',
            'module-1-ros2/ros2-python-nodes',
            'module-1-ros2/urdf-modeling'
          ],
        },
        {
          type: 'category',
          label: 'Module 2: Simulation',
          items: [
            'module-2-simulation/gazebo-simulation',
            'module-2-simulation/unity-visualization'
          ],
        },
        {
          type: 'category',
          label: 'Module 3: NVIDIA Isaac',
          items: [
            'module-3-isaac/isaac-sim',
            'module-3-isaac/nav2-navigation'
          ],
        },
        {
          type: 'category',
          label: 'Module 4: VLA & Capstone',
          items: [
            'module-4-vla/vla-intro',
            'module-4-vla/capstone-project'
          ],
        },
      ],
    },
    {
      type: 'html',
      value: '<span class="menu__link"><b>Reference</b></span>',
    },
    {
      type: 'category',
      label: 'Docusaurus Tutorial',
      collapsed: true,
      items: [
        'intro',
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics',
        },
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras',
        },
      ],
    },
  ],
};

export default sidebars;
